### ISSUE TITLE
DioError [DioErrorType.response] v5.0

### ISSUE THREAD

**Issue by a1ssat** [cfug/dio#1676] opened 2023-02-20 10:52 UTC
### Package

dio

### Version

5.0.0

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.7.3, on linux 6.1.12-zen1-1-zen, locale en_US.UTF-8)
    • Flutter version 3.7.3 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (11 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /opt/android-sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.18+10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.25.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0


[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • linux 6.1.12-zen1-1-zen
    • Chrome (web)    • chrome • web-javascript • Chromium 110.0.5481.100 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Dart Version

2.19.2

### Steps to Reproduce

requests working fine on 4.0.6 but when I upgrade to 5, i got Status: 400 Bad Request https://github.com/cfug/dio/issues/1171

```flutter: ╔╣ Request ║ POST
flutter: ║  https://api.********com/graphql
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ╔ Headers
flutter: ╟ content-type: application/json
flutter: ╟ contentType: application/json
flutter: ╟ responseType: ResponseType.json
flutter: ╟ accept: */*
flutter: ╟ followRedirects: true
flutter: ╟ connectTimeout: null
flutter: ╟ receiveTimeout: null
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
```

### Expected Result

``` ╔╣ Response ║ POST ║ Status: 200 OK
flutter: ║  https://api.********com/graphql
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ╔ Body
flutter: ║
flutter: ║    {
flutter: ║         data: {
flutter: ║             __typename: "Mutation",
flutter: ║             login: {
flutter: ║                 __typename: "Login******",
flutter: ║                 "eyJhbGciOi*********"
flutter: ║                 "eyJhbGciOiJI*************"
flutter: ║            }
flutter: ║        }
flutter: ║    }
flutter: ║
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
```

### Actual Result

```╔╣ DioError ║ Status: 400 Bad Request
flutter: ║  https://api.********com/graphql
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ╔ DioErrorType.badResponse
flutter: ║ POST body missing, invalid Content-Type, or JSON object has no keys.
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝```

**Comment by AlexV525** [comment] 2023-02-20 11:13
This will be resolved by #1671 once the new version is released.

**Comment by aissat** [comment] 2023-02-27 09:14
@AlexV525  this issue not fixed  

```yml

  dio: ^5.0.1
  gql_dio_link: ^0.3.0
  pretty_dio_logger: ^1.3.1
```


```[log] ╔╣ Request ║ POST
[log] ║  https://a*********.com/graphql
[log] ╚══════════════════════════════════════════════════════════════════════════════════════════╝
[log] ╔ Headers
[log] ╟ Accept: */*
[log] ╟ content-type: application/json
[log] ╟ contentType: application/json
[log] ╟ responseType: ResponseType.json
[log] ╟ followRedirects: true
[log] ╟ connectTimeout: null
[log] ╟ receiveTimeout: null
[log] ╚══════════════════════════════════════════════════════════════════════════════════════════╝
[log] DioInterceptor=>onRequest=>path: /graphql
[log] interceptor: refresh expired
[log] ╔╣ DioError ║ Status: 400 Bad Request
[log] ║   https://a*********.com/graphql
[log] ╚══════════════════════════════════════════════════════════════════════════════════════════╝
[log] ╔ DioErrorType.badResponse
[log] ║ POST body missing, invalid Content-Type, or JSON object has no keys.
[log] ╚══════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by AlexV525** [comment] 2023-02-27 09:17
https://github.com/cfug/dio/issues/1648#issuecomment-1429344383

**Comment by aissat** [comment] 2023-02-27 15:14
> [#1648 (comment)](https://github.com/cfug/dio/issues/1648#issuecomment-1429344383)

same thing :-1:

**Comment by AlexV525** [comment] 2023-02-27 17:59
Please provide your minimal reproducible example about the empty body. As a reference, setting up a test like https://github.com/cfug/dio/blob/265e8964b93c699a12dd875100300402db7d14e0/dio/test/options_test.dart#L220 would be helpful to find the root cause.

**Comment by aissat** [comment] 2023-02-27 19:10
@AlexV525 this code  working well with version `4.0.6`
```dart
....
client = Dio(
      BaseOptions(
        baseUrl: 'https://a*********.com/',
        headers: {
          HttpHeaders.userAgentHeader: 'app',
        },
      ),
    );
...
```


```dart
....
client.interceptors.add(AuthInterceptors());
    var dioLink = Link.from([DioLink('/graphql', client: client)]);
    _graphQLClient = GraphQLClient(
      cache: GraphQLCache(store: InMemoryStore()),
      link: dioLink,
    );
...
```

```dart
....
    var queryOpt = QueryOptions(
        document: parseString(query),
        variables: vars,
        fetchPolicy: FetchPolicy.networkOnly);
    var res = await _graphQLClient.query(queryOpt);

    if (res.hasException) throw Exception(res.exception);
...
```
after version `5.0.0`  I got this issues, i tried to add  `contentType` but no thing change

**Comment by AlexV525** [comment] 2023-02-28 01:28
Can you simplify your code with some raw requests? More specifically, we don't know what happened with `QuertOptions`, `client.query`, `Link.from`. It would be better of you can reproduce the exception using a minimal example without any business logic.

**Closed** 2023-03-09 01:43 UTC
Labels: h: need more info, h: need triage, s: bug
