### ISSUE TITLE
Exception has occurred. DioException (DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code. The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled" Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code. )

### ISSUE THREAD

**Issue by adenehemia09** [cfug/dio#2083] opened 2024-01-01 06:49 UTC
### Package

dio

### Version

5.4.0

### Operating-System

Windows

### Output of `flutter doctor -v`

```shell
C:\Users\adene>flutter doctor -v
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22621.2861], locale en-ID)
    • Flutter version 3.16.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (12 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\adene\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[!] Android Studio (version unknown)
    • Android Studio at C:\Users\adene\AppData\Local\Android\Sdk
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine Android Studio version.
    X android-studio-dir = C:\Users\adene\AppData\Local\Android\Sdk
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\adene\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • CPH2269 (mobile)  • 192.168.1.5:35109 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows           • windows-x64    • Microsoft Windows [Version 10.0.22621.2861]
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 120.0.6099.130
    • Edge (web)        • edge              • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.
```

### Dart Version

3.2.3

### Steps to Reproduce

I am currently using an API to log in to my application using DIO as the network service.
Initially, it worked when I entered the email and password correctly.
However, when I entered incorrect email and password data, my application encountered an error.
I have tried various ways to handle this response, but my application still crashes.

I have tried every method to address this error handling issue. However, I still face the same problem.

<img width="960" alt="Screenshot 2024-01-01 134019" src="https://github.com/cfug/dio/assets/83700447/cfa8c618-b264-4a41-a14a-a1436ee1c498">

This is my last attempt to solve this issue. Anyone here, please help me!

### Expected Result

<img width="960" alt="image" src="https://github.com/cfug/dio/assets/83700447/421bb5ad-3678-4769-a212-e84c3b5fad77">

<img width="960" alt="image" src="https://github.com/cfug/dio/assets/83700447/ba23d1cc-3b93-4188-a77c-135ae822e9e4">

### Actual Result

<img width="960" alt="Screenshot 2024-01-01 132359" src="https://github.com/cfug/dio/assets/83700447/19713ab6-38c2-446c-a927-d283d289a247">

**Comment by AlexV525** [comment] 2024-01-01 07:17
Duplicate of #1869. See https://github.com/cfug/dio/issues/1869#issuecomment-1864369025

**Closed by AlexV525** 2024-01-01 07:17 UTC
Labels: h: need triage, s: bug
