### ISSUE TITLE
LogInterceptor causes connection loss in Flutter version 3.13.x

### ISSUE THREAD

**Issue by we-prajapati-c001** [cfug/dio#1970] opened 2023-09-18 06:11 UTC
### Package

dio

### Version

5.2.1+1

### Operating-System

iOS

### Output of `flutter doctor -v`

```shell
[!] Flutter (Channel [user-branch], 3.13.4, on macOS 13.0.1 22A400 darwin-arm64,
    locale en-IN)
    ! Flutter version 3.13.4 on channel [user-branch] at
      /Users/prajapati.c001/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss
      this error.
    • Framework revision 367f9ea16b (5 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/prajapati.c001/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/prajapati.c001/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • testers’s iPhone (mobile) • 00008110-001565341E78401E • ios            •
      iOS 16.6.1 20G81
    • macOS (desktop)           • macos                     • darwin-arm64   •
      macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)              • chrome                    • web-javascript •
      Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Dart Version

3.1.2

### Steps to Reproduce

1. Implement log interceptor for your app
2. send requests to multiple endpoints that return long responses
3. Wait for log "lost connection to device"

---

### OR when you change package code

Cause:
[https://github.com/cfug/dio/blob/main/dio/lib/src/interceptors/log.dart#L138C19](https://github.com/cfug/dio/blob/main/dio/lib/src/interceptors/log.dart#L138C19)

Fix:
```dart
// Note you need to import debugPrint. import 'package:flutter/foundation.dart' show debugPrint;
debugPrint(object.toString());
```

### Expected Result

The log interceptor shouldn't fail, and the device shouldn't lose connection.

### Actual Result

Can't paste whole logs because of company policy,
<img width="259" alt="Screenshot 2023-09-18 at 11 38 21 AM" src="https://github.com/cfug/dio/assets/113423816/078f6237-3e15-4b32-9869-df09752dc53a">

**Comment by we-prajapati-c001** [comment] 2023-09-18 06:12
### This  "lost connection to device" won't happen if you build using Xcode.

### OR when you change package code

Cause:
[https://github.com/cfug/dio/blob/main/dio/lib/src/interceptors/log.dart#L138C19](https://github.com/cfug/dio/blob/main/dio/lib/src/interceptors/log.dart#L138C19)

Fix:
```dart
// Note you need to import debugPrint. import 'package:flutter/foundation.dart' show debugPrint;
debugPrint(object.toString());
```

**Comment by AlexV525** [comment] 2023-09-18 08:40
We cannot take further actions until a minimal reproducible example is provided.

**Comment by we-prajapati-c001** [comment] 2023-09-18 09:28
I can't provide minimal code as I can't test it on a real iOS device with a minimal code app (we aren't allowed to create new app and install it on iPhone which requires new code signing certi and provision)

**Comment by AlexV525** [comment] 2023-09-18 09:59
So native log regarding the crashing might be helpful in this case.

**Comment by we-prajapati-c001** [comment] 2023-09-18 10:24
@AlexV525 Sorry man on the native as well we have no error, no error is there in any logs, it just shows 

lost connection to the device
Exited.

**Comment by AlexV525** [comment] 2023-09-18 10:31
If so, I suspect someone calls `exit`. You might add a breakpoint to see if it's true.

**Comment by kuhnroyal** [comment] 2023-09-18 11:24
You can construct your `LogInterceptor` with a custom logging function.

```dart
LogInterceptor(logPrint: (o) => debugPrint(o.toString()))
```

We can not import `debugPrint` into `dio` since it is not part of the Dart SDK.

**Comment by we-prajapati-c001** [comment] 2023-09-18 12:38
@AlexV525 I'll check
@kuhnroyal Yep, that's what we are doing since 3.13.x release! thanks!

**Comment by AlexV525** [comment] 2023-09-18 13:11
Closing as https://github.com/cfug/dio/issues/1970#issuecomment-1723215033.

**Closed by AlexV525** 2023-09-18 13:11 UTC
Labels: i: wontfix
