### ISSUE TITLE
[dio] Some map response returns null but using Postman can see the field with the correct result

### ISSUE THREAD

**Issue by fakhravari** [cfug/dio#1890] opened 2023-07-10 11:42 UTC
### Package

dio

### Version

5.1.2

### Steps to Reproduce

1

### Expected Result

I test with package http, it shows responce in the output, but it is null in the output dio.

![Screenshot 2023-07-10 150351](https://github.com/cfug/dio/assets/4311975/29d4ed85-5ee4-4afe-be4b-395ed064ed45)

https://github.com/cfug/dio/assets/4311975/000d5930-5225-4b28-89b1-f1cde42de529

### Actual Result

UserName:3501578873
Password:12345
IdLanguage:1

https://mobiletest.pmlm.ir/pisc/v3/LoginCustomer

**Comment by fakhravari** [comment] 2023-07-11 04:14
Future<void> _incrementCounter() async {
    var dio = Dio();
    Map<String, dynamic> queryParameters = {
      "UserName": '3501578873',
      "Password": '12345',
      "IdLanguage ": 1
    };

    var ret = await dio.post('https://mobiletest.pmlm.ir/pisc/v3/LoginCustomer',
        data: queryParameters);

    var url = Uri.parse('https://mobiletest.pmlm.ir/pisc/v3/LoginCustomer');
    var res2 = await http.post(
      url,
      headers: {'Content-Type': 'application/x-www-form-urlencoded'},
      body: jsonEncode(queryParameters),
    );



    var data1 = ret.data.toString();
    var data2 = res2.body.toString();
  }

https://github.com/cfug/dio/assets/4311975/b5c9bd0e-9d02-4803-9c3b-7fa360a75520

**Comment by AlexV525** [comment] 2023-07-14 17:13
I can reproduce this using the below code:
```dart
import 'package:dio/dio.dart';
import 'package:test/test.dart';

void main() {
  test('request something', () async {
    final response = await Dio().post(
      'https://mobiletest.pmlm.ir/pisc/v3/LoginCustomer',
      data: {'UserName': '3501578873', 'Password': '12345', 'IdLanguage ': 1},
    );
    print(response);
  });
}
```

**Comment by fakhravari** [comment] 2023-07-15 06:07
> ```dart
> test
> ```

![Screenshot 2023-07-15 093634](https://github.com/cfug/dio/assets/4311975/fcf75aed-d298-4e67-b072-89447580cc2b)

**Comment by AlexV525** [comment] 2023-07-15 10:51
After debugging what's happened to your requests, the `dio` request is different compared to the `http`.

For `http` request:
- The body will be encoded as UTF-8 bytes in the `HttpClientRequest`, corresponding length: 60.
- The body will be sent exactly as an `application/x-www-form-urlencoded` content as defined.
- The response returns 1562 bytes, with `user: null` and `Authorization: null`.
- The return `AnbarName` is `پست` which corresponds to bytes `[217, 190, 216, 179, 216, 170]`.
- The response bytes are decoded correctly by the decoder.

For `dio` and Postman request:
- The body will be implied as `JSON` content in the `ImplyContentTypeInterceptor` because it's a `Map`, also with `application/json` as the `content-type`.
- The response returns 2588 bytes, with all fields non-null.

To make both requests the same, since `user: null` and `Authorization: null` seems abnormal or invalid, I suggest:
- Do not use `jsonEncode` for `http` request, which corrects the usage of the `http` request.
- Set `Options(contentType: Headers.formUrlEncodedContentType)` when using the `dio` request.

Closing as invalid usages.

### Other issues

I've also found that the name bytes (`[217, 190, 216, 179, 216, 170]`) are not being decoded correctly by the `Utf8Decoder` when it's in the specific response bytes.

Submitted issue: https://github.com/dart-lang/sdk/issues/52942

**Closed by AlexV525** 2023-07-15 10:51 UTC
Labels: p: dio, s: bug
