### ISSUE TITLE
QueuedInterceptorWrapper does not trigger on error, but InterceptorsWrapper does.

### ISSUE THREAD

**Issue by CodeFoxLk** [cfug/dio#1683] opened 2023-02-21 08:06 UTC
### Package

dio

### Version

5.0.0

### Steps to Reproduce

**QueuedInterceptorWrapper does not trigger an error, but InterceptorsWrapper does.**

This is my code to get a refresh token. The problem is when the refresh token response returns an error status of [403]. the error function not triggering. and not execute codes under the [
_dio.post<String>(URLEndPoints.refreshTokenRequest
] post request

but when I use InterceptorsWrapper. it working fine. 

```dart
_dio.interceptors.add(QueuedInterceptorsWrapper(
      onRequest: (options, handler) async {
        final accessToken = await _jwtHandler.getAccessToken();
        if (accessToken != null) {
          // if access token is available
          options.headers['Authorization'] = 'Bearer $accessToken';
        }
        return handler.next(options);
      },
      onResponse: (response, handler) {
        handler.next(response);
      },
      onError: (DioError error, handler) async {
        if (error.response?.statusCode == StatusCode.UNAUTHORIZED) {
          try {
            final Tokens? newTokens = await refreshTokens();

            if (newTokens != null) {
              await _jwtHandler.saveJWT(accessToken: newTokens.accessToken, refreshToken: newTokens.refreshToken);
              AppLogger.logInfo(newTokens.toString());
              //Complete the request with Response object and other error interceptor(s) will not be executed. This will be considered a successful request!
              //handler.resolve() means the error is resolved and stops the other er ror interceptors.
              return handler.resolve(await _retry(error.requestOptions));
            } else {
              //delete remains tokens
              await _netErrorHandler.deleteTokensAndNavigateToAuth();
              return handler.reject(error);
            }
          } on DioError catch (e) {
            AppLogger.logError('AuthInterceptor - Error when retrying with a new Refresh');

            if (e.response?.statusCode == StatusCode.UNAUTHORIZED) {
              AppLogger.logError('AuthInterceptor - Error 401 retrying with a new Refresh');
            }
            rethrow;
          } catch (e) {
            AppLogger.logError('Error during retry - $e');
            rethrow;
          }

          //when 403
        } else if (error.response?.statusCode == StatusCode.FORBIDDEN) {
          await _netErrorHandler.deleteTokensAndNavigateToAuth();
        }

        handler.next(error);
      },
    ));

Future<Tokens?> refreshTokens() async {
    final refreshToken = await _jwtHandler.getRefreshToken();
   
    if (refreshToken == null) {
      return null;
    }
    final response = await _dio.post<String>(URLEndPoints.refreshTokenRequest,
        data: {'token': refreshToken},
        options: Options(headers: {'Content-Type': 'application/json'}));

    if (response.statusCode == StatusCode.OK && response.data != null) {
      AppLogger.logInfo(response.data!);
      final tokens = Tokens.tokenModelFromJson(response.data!);

      return tokens;
    } else {
      //refresh token is invalid
      AppLogger.logError('refresh token not received');
      return null;
    }
  }
```

### Expected Result

trigger onError function after get 403. from [ _dio.post<String>(URLEndPoints.refreshTokenRequest........]

### Actual Result

does not trigger onError function after get 403. from [ _dio.post<String>(URLEndPoints.refreshTokenRequest........]

**Comment by ueman** [comment] 2023-02-22 18:19
Hey, thanks for the report. Are you willing to submit a fix in a PR?

**Comment by llfbandit** [comment] 2023-03-01 13:20
The issue is related to `QueuedInterceptorsWrapper` or `QueuedInterceptor` where you make other requests inside.

Since this kind of interceptor provides a sequential processing of each event, when you make a request returning an invalid status the `onError` event is not triggered while you are in the currently running scope, the response is considered in "pending state" regarding the queue.

**Comment by CodeFoxLk** [comment] 2023-03-05 15:25
@llfbandit How do I manually change that pending state? Is there a way to do it?

**Comment by llfbandit** [comment] 2023-03-05 15:31
You must use another client without your jwt interceptor. Use it also for your retry request otherwise you will be in the same situation in case of unsuccessful request.

**Comment by AlexV525** [comment] 2023-03-12 16:53
From your code, we don't know what's happening with your handler*, but as @llfbandit suggested, a new `Dio` client should be used inside the token refresh request. See [the example](https://github.com/cfug/dio/blob/main/example/lib/queued_interceptor_crsftoken.dart) for more details.

**Closed by AlexV525** 2023-03-12 16:53 UTC
Labels: h: need triage, s: bug

**Comment by farmanteachedison** [comment] 2023-07-28 11:57
hi, @CodeFoxLk have you found the answer?

**Comment by rashmisridar** [comment] 2024-11-27 12:11
Hi @CodeFoxLk @AlexV525  any update on this. In the latest version getting the same issue https://github.com/cfug/dio/issues/2335
