### ISSUE TITLE
Frequent bad file descriptor errors on iOS

### ISSUE THREAD

**Issue by wahkim** [cfug/dio#1908] opened 2023-07-26 06:34 UTC
### Package

dio

### Version

5.1.1

### Steps to Reproduce

We deployed a Flutter application and noticed that our file uploads were frequently showing this exception:
`SocketException: OS Error: Bad file descriptor, errno = 9, address = <redacted domain>, port = 64436`

code：
`Dio dio = new Dio();
      (dio.httpClientAdapter as IOHttpClientAdapter).onHttpClientCreate = (client) {
        client.badCertificateCallback = (cert, host, port) {
          return true;
        };
        client.connectionTimeout = Duration(seconds: 5);
      };
      dio.options.contentType = contentType;
      File file = File(filePath);
      int fileLength = file.lengthSync();
      var response = await dio.put(
        url,
        data: file.openRead(),
        cancelToken: cancelToken,
        onSendProgress: (count, total) {
          print('上传onSendProgress count=${count}, total=${total}');
        },
        onReceiveProgress: (count, total) {
        },
        options: Options(headers: {
          Headers.contentLengthHeader: fileLength, 
        }),
      );`

### Expected Result

File uploaded successfully！

### Actual Result

Failed to upload file！
```[tasklist]
### Tasks
```

**Comment by kuhnroyal** [comment] 2023-07-26 14:26
Which OS? Is this iOS?

**Comment by AlexV525** [comment] 2023-07-27 02:45
Duplicate of #1779.

**Closed by AlexV525** 2023-07-27 02:45 UTC
Labels: h: need triage, s: bug
