### ISSUE TITLE
FormData.fromMap is encoding request body automatically

### ISSUE THREAD

**Issue by jagadmitul** [cfug/dio#1741] opened 2023-03-16 11:20 UTC
### Package

dio

### Version

5.0.2

### Dart Version

2.19.2

### Steps to Reproduce

```
Future<FormData> mapToFormData(
  Map<String, dynamic> formData,
) async {
  try {
    return FormData.fromMap(formData);
  } catch (e) {
    rethrow;
  }
}
```

### Expected Result

The above code should return request body as:

- item[0][product_size_id]: 14

### Actual Result

Instead of the expected result the code is returning request body as:

- items%5B0%5D%5Bproduct_size_id%5D: 14

**Comment by katjai1** [comment] 2023-03-17 13:13
Yes, working.

**Comment by AlexV525** [comment] 2023-03-17 13:16
So this might be a regression invented from #1704. cc @kuhnroyal

**Comment by kuhnroyal** [comment] 2023-03-17 14:17
Can you please add your input `formData` map to the issue.

**Comment by katjai1** [comment] 2023-03-17 20:16
Thanks a lot!

**Comment by katjai1** [comment] 2023-03-21 22:07
Seems an issue still in place. With 5.0.1 on the backend server I had in POST vars:  

{"a": 1, "b": 2, "c": 3} 

With 5.0.3 the same looks like:

[{"a": 1, "b": 2, "c": 3}] 

Seems POST map wrapped with the additional List somehow.

**Comment by kuhnroyal** [comment] 2023-03-21 23:50
Please provide me with a reproducible sample, then I can fix this asap.

**Comment by kuhnroyal** [comment] 2023-03-22 11:04
I don't see how this can be happening.

This test succeeds:
```dart
  test('post map', () async {
    final dio = Dio()
      ..options.baseUrl = EchoAdapter.mockBase
      ..httpClientAdapter = EchoAdapter();

    final response = await dio.post(
      '/post',
      data: {'a': 1, 'b': 2, 'c': 3},
    );
    expect(response.data, '{"a":1,"b":2,"c":3}');
    expect(response.statusCode, 200);
  });
```

**Comment by katjai1** [comment] 2023-03-22 13:43
Here is a real case for Flutter web application. I'm sending:

`dio.FormData.fromMap({'_mpc_api': {'dest': '/', 'data': {'a': 1, 'b': 2, 'c': 3}}}, dio.ListFormat.multiCompatible);`

In 5.0.1 request is:

```
----dio-boundary-4271291696
content-disposition: form-data; name=“_mpc_api[dest]”
/
----dio-boundary-4271291696
content-disposition: form-data; name=“_mpc_api[data][a]”
1
----dio-boundary-4271291696
content-disposition: form-data; name=“_mpc_api[data][b]”
2
----dio-boundary-4271291696
content-disposition: form-data; name=“_mpc_api[data][c]”
3
----dio-boundary-4271291696--

```
In 5.0.3

```
----dio-boundary-3699245676
content-disposition: form-data; name=“_mpc_api[dest]”
/
----dio-boundary-3699245676
content-disposition: form-data; name=“_mpc_api[data]”
{a: 1, b: 2, c: 3}
----dio-boundary-3699245676--
```

**Comment by katjai1** [comment] 2023-03-22 18:09
I can confirm that this issue is a web-only seems. Everything is fine on IOS, Android and tests. Something is going wrong here (check fields, MapEntry _mpc_api[data] converted to the string): 

![screenshot](http://katya.eu/i/dio.jpg)

**Comment by kuhnroyal** [comment] 2023-03-22 20:49
I don't know, looks like the value is a `String`. It must have gone wrong before this but there is no separate implementation for the browser for the encoding.

**Comment by kuhnroyal** [comment] 2023-03-22 21:51
I changed more formdata tests to run on browser but they alls succeed. Please try to debug `FormData.fromMap` and `encodeMap()`.

**Comment by katjai1** [comment] 2023-03-23 18:58
I've found the source of a problem: it's happens when some part of a data is presented as Map<dynamic, dynamic>. Here is a test for that case:

 ```
 test('fromMap with dynamic Map inside', () async {
    Map dynamicData = {
      'a': 1,
      'b': 2,
      'c': 3,
    };

    Map<String, dynamic> request = {
      'api': {'dest': '/', 'data': dynamicData}
    };

    final fd = dio.FormData.fromMap(request);
    final data = await fd.readAsBytes();
    final result = utf8.decode(data, allowMalformed: true);
    expect(result, contains('name="api[dest]"'));
    expect(result, contains('name="api[data][a]"'));
    expect(result, contains('name="api[data][b]"'));
    expect(result, contains('name="api[data][c]"'));
  });

```

**Comment by kuhnroyal** [comment] 2023-03-23 19:06
That makes sense, it was one thing that came to mind when I reviewed my last PR. I think the maps should always have a String key so we probably need to improve the typing. But you should be able to work around the problem.

**Comment by katjai1** [comment] 2023-03-23 19:07
Yes, this issue already fixed in our codebase.

**Closed** 2023-03-27 04:00 UTC
Labels: p: dio, s: bug, b: regression
