### ISSUE TITLE
Freeze on large file download with dio.download

### ISSUE THREAD

**Issue by YaWaiAung** [cfug/dio#1356] opened 2021-12-25 13:52 UTC
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name              |  flutter / android                          |      |
| Platform Version               |   2.2.3    / api 28                     |      |
| Dio Version                    | 4.0.4                                |      |

### Issue Description 

Got freezed on downloading large file (movie file eg. mp4,mkv).
It's back when downloading done. 
User can't press any button on screen until downloading done.

### My Code 
``` 
await _dio.download(model.url, savePath,
          onReceiveProgress: (received, total) {
        if (total != -1) {
          model.progress =
              int.parse((received / total * 100).toStringAsFixed(0));
          _showNotification(model);
        }
      }) 
```

**Comment by kuhnroyal** [comment] 2021-12-26 14:05
Probably a duplicate of https://github.com/flutterchina/dio/issues/1328
Try the new build from there please

**Comment by ayush221b** [comment] 2022-04-13 11:56
Hey, I am facing the same issue, on a similar implementation. Any word on this?

**Closed** 2023-02-13 04:03 UTC
Labels: bug
