### ISSUE TITLE
DioException [DioExceptionType.receiveTimeout] not working

### ISSUE THREAD

**Issue by Apichate-Y** [cfug/dio#1868] opened 2023-06-15 10:28 UTC
### Package

dio

### Version

5.2.0

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-TH)
    • Flutter version 3.7.12 on channel stable at /Users/apichete/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (8 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/apichete/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.79.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.106

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Dart Version

2.19.6

### Steps to Reproduce

No

### Expected Result

I set the duration but it doesn't work. The previous version is not

### Actual Result

<img width="620" alt="Screenshot 2566-06-15 at 17 19 07" src="https://github.com/cfug/dio/assets/49363526/e07dccb7-cfb4-4ada-a7e7-e8e80147396f">

**Comment by AlexV525** [comment] 2023-06-15 10:32
Thanks for the report. Please fill in information about what device you are using to test, and better to provide a minimal reproducible example.

**Comment by kuhnroyal** [comment] 2023-06-16 17:13
Is this new with 5.2.0 or something you also experienced before?

**Comment by Velkamhell97** [comment] 2023-06-17 16:10
I did some tests and it happens since version 5.2.0, with version 5.1.2 it works correctly and catches the exception.

**Comment by kuhnroyal** [comment] 2023-06-17 16:38
Then it is probably related to the changes in https://github.com/cfug/dio/pull/1836

**Comment by Velkamhell97** [comment] 2023-06-17 17:06
I hope that can fix this in later versions

**Comment by AlexV525** [comment] 2023-06-17 17:06
> I did some tests and it happens since version 5.2.0, with version 5.1.2 it works correctly and catches the exception.

Could you do a `git bisect` from 5.1.2 to 5.2.0 to find out which commit causes the issue?

**Comment by AlexV525** [comment] 2023-06-20 10:37
@Velkamhell97 I think your problem should be a duplicate of #1869.

**Comment by AlexV525** [comment] 2023-06-20 10:40
@Apichate-Y Can you provide more details?

**Comment by Velkamhell97** [comment] 2023-06-20 17:18
@AlexV525 The option `Uncaught Exceptions` is very useful to recognize and detect all the possible exceptions that can be thrown in our application and this way to give a specific treatment to each one of them or at least to the most important ones, without this option all the exceptions can be handled by a single `try-catch`, losing error information, especially when we create our customized exceptions. I know that disabling this option the exception is caught at some point, but something had to have changed between version 5.1.2 and version 5.2.0 because running the same code that I showed above with 5.1.2 verions the exception is caught even with the Uncaught Exceptions enabled. 

The bug starts exactly in this commit 04a158c318fbc73a7b590ab4365e5390aebd35f1. I hope it helps, thank you very much to all contributors for this great package.

**Comment by Velkamhell97** [comment] 2023-06-21 20:08
What bad thing did I say?

**Comment by AlexV525** [comment] 2023-06-21 23:21
There's no bad thing, you'll need to follow up the issue I've mentioned.

**Comment by Apichate-Y** [comment] 2023-06-22 07:20
@AlexV525  In the new version I got it fixed, thank you.

**Closed** 2023-06-22 08:44 UTC
Labels: h: need more info
