### ISSUE TITLE
Version 5.5.0 brakes the web build

### ISSUE THREAD

**Issue by ifuterman** [cfug/dio#2264] opened 2024-07-03 09:38 UTC
### Package

dio

### Version

5.5.0

### Operating-System

Web

### Adapter

Default Dio

### Dart Version

3.4.3

### Steps to Reproduce

Build a minimal web application
The problem seems like you forgot to change the version of dio_web_adapter-1.0.0 to dio_web_adapter-1.0.1

### Expected Result

Succesful build

### Actual Result

Run flutter build web --web-renderer canvaskit --dart-define=API_URL="***" --dart-define=ORIGIN_URL="***" --dart-define=WEB_API_KEY="***" --dart-define=DEPLOY_TYPE="STAGE" --dart-define=AWS_REGION="us-west-2" --dart-define=AWS_ACCESS_KEY="***" --dart-define=AWS_SECRET_KEY="***" --dart-define=AWS_IMAGE_BUCKET="***pictures" --dart-define=AWS_IMAGE_KEY_PREFIX="dev/"

Compiling lib/main.dart for the Web...                          
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../../../.pub-cache/hosted/pub.dev/dio_web_adapter-1.0.0/lib/src/html/adapter.dart:149:9:
Error: The method 'debugLog' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio_web_adapter/src/html/adapter.dart' ('../../../.pub-cache/hosted/pub.dev/dio_web_adapter-1.0.0/lib/src/html/adapter.dart').
        debugLog(
        ^^^^^^^^
../../../.pub-cache/hosted/pub.dev/dio_web_adapter-1.0.0/lib/src/html/adapter.dart:155:9:
Error: The method 'debugLog' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio_web_adapter/src/html/adapter.dart' ('../../../.pub-cache/hosted/pub.dev/dio_web_adapter-1.0.0/lib/src/html/adapter.dart').
        debugLog(
        ^^^^^^^^
../../../.pub-cache/hosted/pub.dev/dio_web_adapter-1.0.0/lib/src/html/adapter.dart:271:9:
Error: The method 'debugLog' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio_web_adapter/src/html/adapter.dart' ('../../../.pub-cache/hosted/pub.dev/dio_web_adapter-1.0.0/lib/src/html/adapter.dart').
        debugLog(
        ^^^^^^^^
Error: Compilation failed.
  Command: /opt/hostedtoolcache/flutter/stable-3.22.2-x64/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/hostedtoolcache/flutter/stable-3.22.2-x64/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/opt/hostedtoolcache/flutter/stable-3.22.2-x64/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DAPI_URL=*** -DORIGIN_URL=*** -DWEB_API_KEY=*** -DDEPLOY_TYPE=STAGE -DAWS_REGION=us-west-2 -DAWS_ACCESS_KEY=*** -DAWS_SECRET_KEY=*** -DAWS_IMAGE_BUCKET=***pictures -DAWS_IMAGE_KEY_PREFIX=dev/ -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true --native-null-assertions --no-source-maps -o /home/runner/work/dashboard/dashboard/.dart_tool/flutter_build/6e554552c7c34a4d703f7f2275eb1ad5/app.dill --packages=.dart_tool/package_config.json --cfe-only /home/runner/work/dashboard/dashboard/.dart_tool/flutter_build/6e554552c7c34a4d703f7f2275eb1ad5/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:193:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             27.1s
Error: Failed to compile application for the Web.
Error: Process completed with exit code 1.

**Comment by AlexV525** [comment] 2024-07-03 09:41
Duplicate of https://github.com/cfug/dio/issues/2262

**Closed by AlexV525** 2024-07-03 09:41 UTC
Labels: h: need triage, s: bug
