### ISSUE TITLE
Running Gradle task 'assembleProfile'.. ../../../.pub-cache/hosted/pub.dev/dio-5.4.3/lib/src/ form_data.dart:175:54: Error: The argument type 'List <int>' can't be assigned to the parameter type 'Uint8list'.

### ISSUE THREAD

**Issue by ShuangZiMoYin** [cfug/dio#2186] opened 2024-04-15 05:46 UTC
### Package

dio

### Version

5.4.3+1

### Operating-System

Android, iOS

### Adapter

Default Dio

### Steps to Reproduce

Running Gradle task 'assembleProfile'..
../../../.pub-cache/hosted/pub.dev/dio-5.4.3/lib/src/
form_data.dart:175:54: Error: The argument type 'List
<int>' can't be assigned to the parameter type
'Uint8list'.
- 'list' is from 'dart:core'.
- 'Uint8List' is from 'dart:typed_data'.
void writeAscii(String s) => controller.add(utf8.
encode(s));
./../.pub-cache/hosted/pub.dev/dio-5.4.3/lib/src/
form_data.dart:176:58: Error: The argument type 'List
<int>' can't be assigned to the parameter type
'Uint8list'.
- 'list' is from 'dart:core'.
- 'Uint8List' is from 'dart:typed_data'.
void writeUtf8(String string) => controller.add(u
itf8.encode(string));

### Expected Result

1

### Actual Result

1

**Comment by AlexV525** [comment] 2024-04-15 05:48
Duplicate of #2184

**Closed by AlexV525** 2024-04-15 05:48 UTC
Labels: h: need triage, s: bug
