### ISSUE TITLE
DioException/Error Stack Trace has memory addresses and offsets instead of function names

### ISSUE THREAD

**Issue by ahmdaeyz** [cfug/dio#1879] opened 2023-06-23 07:42 UTC
### Package

dio

### Version

5.2.1+1

### Output of `flutter doctor -v`

```shell
[!] Flutter (Channel stable, 3.10.5, on macOS 12.6 21G115 darwin-arm64, locale en-EG)
    • Flutter version 3.10.5 on channel stable at /Users/ahmdaeyz/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ahmdaeyz/development/flutter. Consider adding /Users/ahmdaeyz/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (9 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ahmdaeyz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ahmdaeyz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/ahmdaeyz/Downloads/sympols/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.71.0)
    • VS Code at /Users/ahmdaeyz/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Dart Version

Flutter 3.10.5, Dart 3.0.5

### Steps to Reproduce

We have an error interceptor that sends the errors to a Slack channel (Only for our beta users ofc). We sometimes get this as the stack trace instead of normal stack trace.

### Expected Result

Consistent behaviour, Always get the normal stack trace with function names. Or at least tell me how to decrypt this.

### Actual Result

This is the stack trace on the DioError/DioException object.
This was a GET request and the `DioExceptionType` is `badResponse` (this is just an example but most of the time it happens with this type)
response:
           responseExtra: {}
           statusCode: 401
           statusMessage: Unauthorized
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 14175, tid: 6099480576, name io.flutter.1.ui
os: ios arch: arm64 comp: no sim: no
isolate_dso_base: 111f84000, vm_dso_base: 111f84000
isolate_instructions: 111f914c0, vm_instructions: 111f8b9c0
   #00 abs 00000001128bfb9f _kDartIsolateSnapshotInstructions+0x92e6df
   #01 abs 00000001120c48fb _kDartIsolateSnapshotInstructions+0x13343b
   #02 abs 00000001128ea547 _kDartIsolateSnapshotInstructions+0x959087
   #03 abs 00000001128bea4f _kDartIsolateSnapshotInstructions+0x92d58f
   #04 abs 00000001128ea49b _kDartIsolateSnapshotInstructions+0x958fdb
   #05 abs 00000001128e99b3 _kDartIsolateSnapshotInstructions+0x9584f3
   #06 abs 00000001128e9763 _kDartIsolateSnapshotInstructions+0x9582a3
   #07 abs 000000011289113f _kDartIsolateSnapshotInstructions+0x8ffc7f
   #08 abs 00000001128ade1f _kDartIsolateSnapshotInstructions+0x91c95f
   #09 abs 0000000111fa7107 _kDartIsolateSnapshotInstructions+0x15c47
   #10 abs 0000000111fa7453 _kDartIsolateSnapshotInstructions+0x15f93
   #11 abs 00000001128ae05f _kDartIsolateSnapshotInstructions+0x91cb9f
   #12 abs 0000000111fa59df _kDartIsolateSnapshotInstructions+0x1451f
   #13 abs 0000000111fa6753 _kDartIsolateSnapshotInstructions+0x15293
   #14 abs 00000001128915a7 _kDartIsolateSnapshotInstructions+0x9000e7
   #15 abs 000000011289113f _kDartIsolateSnapshotInstructions+0x8ffc7f
   #16 abs 00000001128ade1f _kDartIsolateSnapshotInstructions+0x91c95f
   #17 abs 0000000111fa7107 _kDartIsolateSnapshotInstructions+0x15c47
   #18 abs 00000001127949ff _kDartIsolateSnapshotInstructions+0x80353f
   #19 abs 0000000112892243 _kDartIsolateSnapshotInstructions+0x900d83
   #20 abs 00000001128ae573 _kDartIsolateSnapshotInstructions+0x91d0b3
   #21 abs 0000000111fa75df _kDartIsolateSnapshotInstructions+0x1611f
   #22 abs 000000011278b7f7 _kDartIsolateSnapshotInstructions+0x7fa337
   #23 abs 00000001129b76a7 _kDartIsolateSnapshotInstructions+0xa261e7
   #24 abs 000000011278ba6f _kDartIsolateSnapshotInstructions+0x7fa5af
   #25 abs 0000000111fa6407 _kDartIsolateSnapshotInstructions+0x14f47
   #26 abs 00000001128ad1f3 _kDartIsolateSnapshotInstructions+0x91bd33
   #27 abs 0000000111fa637f _kDartIsolateSnapshotInstructions+0x14ebf
```

**Comment by AlexV525** [comment] 2023-06-23 13:38
This doesn't seem to be a Dart `StackTrace` but a native iOS stace trace. Please identify if it's sent from a Dart code, or maybe something like Sentry caught this.

**Comment by kuhnroyal** [comment] 2023-06-23 16:28
Are you using the native adapter?

**Comment by ahmdaeyz** [comment] 2023-06-26 07:35
Hey @AlexV525, This is from dart code I'm literally using the `stackTrace` property on the `DioError` class:
 
![image](https://github.com/cfug/dio/assets/36048466/08d3ded1-e735-4e52-a63f-68b3b70ac22f)

**Comment by ahmdaeyz** [comment] 2023-06-26 07:39
@kuhnroyal Yes, we are currently using the native adapter.

**Comment by kuhnroyal** [comment] 2023-07-02 13:51
Then it is probably something going on in the cronet or cupertino http libraries. Can you specify version and OS where this happens?

**Comment by ahmdaeyz** [comment] 2023-07-03 10:41
The last time this happened on *Android*
with `dio: ^5.2.1+1`
Device Model: `SM-A326B` 
Android version: `13`
#
The last time this happened on *iOS*
with `dio: ^5.2.1+1`
Device Model: `iPhone 14 Pro`
iOS Version: `16.5`

**Comment by kuhnroyal** [comment] 2023-07-03 10:52
Ok, so this happens on both OS. Are the stacktraces different per OS and do you have obfuscation enabled?

**Comment by ahmdaeyz** [comment] 2023-07-11 08:05
I have it enabled on Android not iOS. I can confirm that this doesn't happen for all the stacktraces that are sent. Only a handful of them.

**Comment by AlexV525** [comment] 2023-08-15 07:43
`_kDartIsolateSnapshotInstructions` means exceptions that happened in the Dart Isolates are not symbolized. You'll need to split your debug info from the Flutter tool when building the add and recover the exact cause from these traces.

At this point, we cannot offer any help. Please submit more precise information if you managed to recover the cause. Closing as won't fix.

**Closed by AlexV525** 2023-08-15 07:43 UTC
Labels: h: need more info, i: out of support, i: no useful information
