### ISSUE TITLE
Status codes meaning

### ISSUE THREAD

**Issue by afekhar** [cfug/dio#2329] opened 2024-11-21 06:06 UTC
### Package

dio

### Version

5.7.0

### Operating-System

Android

### Adapter

Default Dio

### Steps to Reproduce

Post false credentials to sign-in api en

### Expected Result

The status code of 401 has the following meaning: : "unauthorized access due to invalid or missing credentials"

### Actual Result

The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"

**Comment by AlexV525** [comment] 2024-12-16 12:54
Closing as intended. We don't want to reference all status code meanings here which is redundant. The MDN link has been provided through the exception.

**Closed by AlexV525** 2024-12-16 12:54 UTC
Labels: h: need triage, s: bug
